### ISSUE TITLE
Mobile number auto verification not working

### ISSUE THREAD

**Issue by dineshoffl1** [MSG91/sendotp-android#1]
Mobile number OTP auto verification not working if mobile's android version greater than marshmallow.
my mobile is moto and os is nougat its does not auto verified received Otp . can please tell me what was the issue

**Comment by rakshitsoni02** [comment]
You need to add SMS read permission in the manifest file as well check & request SMS permission before making a request of OTP if the API level greater than 22 

`final private int REQUEST_CODE_ASK_PERMISSIONS = 123;       

  if(Build.VERSION.SDK_INT < 23){
     //drectly `request OTP` here
   }else {
    requestSMSPermission();
   } 

private void requestSMSPermission() {

   int hasContactPermission =ActivityCompat.checkSelfPermission(context,Manifest.permission.RECEIVE_SMS);

   if(hasContactPermission != PackageManager.PERMISSION_GRANTED ) {
    ActivityCompat.requestPermissions(Context, new String[]   {Manifest.permission.RECEIVE_SMS}, PERMISSION_REQUEST_CODE);
   }else {
    //Toast.makeText(AddContactsActivity.this, "Contact Permission is already granted", Toast.LENGTH_LONG).show();
     }
}


@Override
public void onRequestPermissionsResult(int requestCode, String[]           permissions, int[] grantResults) {
switch (requestCode) {
    case REQUEST_CODE_ASK_PERMISSIONS:
        // Check if the only required permission has been granted
        if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            Log.i("Permission", "Contact permission has now been granted. Showing result.");
`Request OTP`
            Toast.makeText(this,"Contact Permission is Granted",Toast.LENGTH_SHORT).show();
        } else {
            Log.i("Permission", "Contact permission was NOT granted.");
         } 
         break;
  }
}.`
