### ISSUE TITLE
OTP - Voice call issue after updating to new SDK.

### ISSUE THREAD

**Issue by bhavifm** [MSG91/sendotp-android#13]
Hi Team,

After updating SDK.

We are having an issue in voice otp , here is what we are doing by using msg91 sdk

 mVerification = SendOtpVerification.createSmsVerification
                (SendOtpVerification
                        .config(getE164Number())
                        .context(getContext())
                        .autoVerification(true)
                        .senderId("SP****")
                        .otp(randomOtpString)
                        .build(), this);
        mVerification.initiate();

 mVerification.resend("voice");

Note:  We are just calling "mVerification.resend("voice"); " to initiate a call.

**Comment by iamrajendra** [comment]
We are working on the issue, soon update  you

**Comment by iamrajendra** [comment]
As per our session and discussion, there was no issue found in the code.

**Comment by IrshadAndroid** [comment]
As per our session and discussion, there was no issue found in the code.

**Comment by bhavifm** [comment]
@IrshadWalker  Thanks,

As we observed in session discussion some scenario otp  and voice otp is not receiving.

Scenario:
1. User1-   Here user is able to receive text otp and voice call is not getting.
2. User2 - here user is not able to receive otp and able to receive voice otp call.
3. User3 - Here user is not able to receive otp and not getting voice otp call also.

Note : often users facing above issue. we would like to know what might be the root cause.

**Comment by bhavifm** [comment]
@IrshadWalker  Thanks,

As we observed in session discussion some scenario otp  and voice otp is not receiving.

Scenario:
1. User1-   Here user is able to receive text otp and voice call is not getting.
2. User2 - here user is not able to receive otp and able to receive voice otp call.
3. User3 - Here user is not able to receive otp and not getting voice otp call also.

Note : often users facing above issue. we would like to know what might be the root cause.

**Comment by EffyCoder** [comment]
@bhavifm @IrshadWalker The same is happening with us too. 
As far as I observed, OTP via call is not received on Airtel Numbers.

**Comment by iamrajendra** [comment]
@EffyCoder 

Hi, I checked the OTP and voice OTP with one of the airtel number and it is working fine.
I think your number is under  DND  from the service provider. please try another airtel number.

**Comment by EffyCoder** [comment]
@iamrajendra It worked later on. It's quite unusual behavior.
