### ISSUE TITLE
Use SMS retriever API for automatically detecting OTP

### ISSUE THREAD

**Issue by EffyCoder** [MSG91/sendotp-android#18]
Use SMS retriever API for automatically detecting OTP.
According to new google play console policies it's not allowing us to use SMS read write permissions. It's advising us to use SMS retriever API instead for phone verification purpose.
Please check below link
[SMS retriever API](https://developers.google.com/identity/sms-retriever/overview).

**Comment by iamrajendra** [comment]
This is already in pipeline. In the next build, we will give the auto verification feature which is as per the google guideline.

**Comment by IrshadAndroid** [comment]
Thank you for feedback kindly use SDK version for the above query[1.3.1](https://github.com/MSG91/sendotp-android)
