### ISSUE TITLE
OTP sms not going

### ISSUE THREAD

**Issue by Amey111** [MSG91/sendotp-android#24]
Hello,
  I am unable to send verification OPT through sms. I am getting "Request Unsuccessful Try Again" error.
 The code is as follows-
   mVerification= SendOtpVerification.createSmsVerification
                (SendOtpVerification
                        .config(whole_phone_number1)
                        .context(MyApplication.context)
                        .senderId("SamipA")
                        .autoVerification(true)
                        .build(),this);//;this);//(VerificationListener) getApplicationContext());
        mVerification.initiate();

 The error I am capturing the the following function-

  public void onInitiationFailed(Exception paramException) {
        Log.e("OTP Sent Failed code-",""+paramException.getMessage());
        Toast.makeText(MyApplication.context,"Error- OTP cannot be send. Please try again !",Toast.LENGTH_LONG).show();      
    }

**Comment by IrshadAndroid** [comment]
please use.autoVerification(false) for SMS with OTP on version [1.1](https://github.com/MSG91/sendotp-android/tree/version_1.1)
kindly use the new version of SDK for better experience [1.3.1](https://github.com/MSG91/sendotp-android)
