### ISSUE TITLE
REQUEST UNSUCCESSFUL, TRY AGAIN.

### ISSUE THREAD

**Issue by Seema2020** [MSG91/sendotp-android#25]
Most of the android device in getting this error "Request Unsuccessful, Try Again ", so not getting OTP. Msg91 library stop processing to onInitiationFailed this position. 

Open this url :
1)  https://drive.google.com/drive/folders/1epf213oHV8zks3eRjR1YqU5Wn5PDv4tB?usp=sharing
2) https://drive.google.com/file/d/1CNOZT1JhuuoyI0lptu50C8YvS5HHX_PM/view
3) https://downloads.intercomcdn.com/i/o/165547740/7b896bc269e36762053435b2/image.png

Please check this :
1) VIVO, LAVA & Other mobile in check your official msg91 apk
2) Please https://github.com/MSG91/sendotp-android
3) VIVO mobile in apk run after enter on that number **********, then next after getting REQUEST UNSUCCESSFULL, try again error

2 days continue with your msg91 support via call & livechat, but not getting satisfied answered.
Thank you.

**Comment by IrshadAndroid** [comment]
Thank you for your valuable feedback, please use .httpsConnection(false) for [1.1](https://github.com/MSG91/sendotp-android/tree/version_1.1)
kindly use the new version of SDK for better experience [1.3.1](https://github.com/MSG91/sendotp-android)
