### ISSUE TITLE
initialize failed invalid applicationId SendOTP.initializeApp(context,applicationId);

### ISSUE THREAD

**Issue by VivekChodvadiya** [MSG91/sendotp-android#29]
I am getting this issue

Android Version 4.0
I don't have multi flavour app

I have added this line in my mainactivity
SendOTP.initializeApp(getApplication(), BuildConfig.APPLICATION_ID);

In build Gradle --

        buildConfigField "String", "SEND_OTP_KEY", '"************"'

In my otp verification activity --

      new SendOTPConfigBuilder()
                .setCountryCode(countryCode)
                .setMobileNumber(phoneNumber)
                .setVerifyWithoutOtp(withoutOtp)//direct verification while connect with mobile network
                .setAutoVerification(getActivity())//Auto read otp from Sms And Verify
                .setSenderId("***")
                .setMessage("OTP : ##OTP## for verification. ***** family welcomes you!\n")
                .setOtpLength(4)
                .setVerificationCallBack(this).build();

        SendOTP.getInstance().getTrigger().initiate();

![Screenshot 2020-06-15 at 5 06 58 PM](https://user-images.githubusercontent.com/30853408/84653721-8bac4980-af2b-11ea-9ad1-a4fabce48e62.png)

**Comment by IrshadAndroid** [comment]
hi VivekChodvadiya,
I think the problem you are facing due to your BuildConfig.APPLICATION_ID value and your real package name are different like example "com.android.example" its a folder path now in your case you have to put your the exact folder path instead of  BuildConfig.APPLICATION_ID

**Comment by VivekChodvadiya** [comment]
Ohh shit! I have wasted 10 days on this issue. Finally this solution is worked for me.
