### ISSUE TITLE
Autoverification Not Working in Release Apk

### ISSUE THREAD

**Issue by akshayshenoy38** [MSG91/sendotp-android#32]
Autoverification works in debug apk but in Release apk , we could not get Autoverification Response code.

**Comment by AdityaIsHere** [comment]
Checking the same

**Comment by AdityaIsHere** [comment]
Hello @akshayshenoy38 are you using the Release aab bundle or APK? we checked the issue reported by you with release aab and the release bundle works fine for us with the normal settings provided in Readme file, could you please share more details here? and also please share the logs for the time you request OTP

**Comment by akshayshenoy38** [comment]
Hi Sir,
       I am using Release APK, When I sent Release Apk to client, using
Drive, it was not working,
READ_OTP_SUCCESS Response was not coming through SEND_OTP Listeners.

Video -
https://drive.google.com/file/d/1_81HRbBZavu8jVo19i6szGQHvn8e20BG/view?usp=sharing

But when I Updated it to Playstore, and Downloaded latest Release from
There, it Worked. is it like security thing?

**Comment by akshayshenoy38** [comment]
For Debug Build Logs.
[image: image.png]

For Release Build Log. , after we manually enter otp. Autoverification
Response was not coming.
[image: image (1).png]


Target SDK Version 28,
Minimum SDK version 17.

**Comment by AdityaIsHere** [comment]
Hi @akshayshenoy38 
yes that might be the reason, because the Release APK is supposed to be uploaded to play store & also now .aab bundle is supposed to be uploaded on play store, as Play store slices the APK for each device dependent on Android OS version and make. 
So, my suggestion either share the debug APK for testing or upload the release APK on Play store Internal track / Alpha / Beta testing. That is the correct way for testing. I hope you got the solution to this, if not, please let me know any other difficulties you are facing. 
Will be happy to help. 
Thanks 
Aditya

**Comment by akshayshenoy38** [comment]
Hi Sir,
     Thanks a lot,. let me know if issue has to be closed, because I
didnt try internal track. sent in drive, as its working in playstore anyway.

I wanted to ask weather version 1.3.3 works backwards till minsdk 17,
because for version 17 and 18  .

Thanks amd Regards,
Akshay Shenoy

**Comment by akshayshenoy38** [comment]
Hi Sir,

I wanted to ask weather version 1.3.3 works backwards till minsdk 17,
because for version 17 and 18  .
   I was getting crash when I trigger .

[image: image.png]


. will check and raise it as separate issue. as the users we target can be
using older devices.
[image: Screenshot from 2020-08-21 14-02-57.png]

**Comment by akshayshenoy38** [comment]
[image: image.png]

**Comment by akshayshenoy38** [comment]
Hi Sir, Thanks a lot,. let me know if issue has to be closed, because I
used to update APK, maybe it doesn't work in the Drive. sent in drive, as
its working in playstore . I also wanted to ask weather version 1.3.3 works
backwards till minsdk 17, because for version 17 and 18 . I was getting
crash when I trigger SendOTP.getInstance().trigger().initiate();

[image: image.png]
Thanks and Regards,

**Comment by akshayshenoy38** [comment]
Hi Sir,
      If I Use Version 1.3.8, Now Crash is not there, but when I try
logging in, im not getting response in Pixel Emulators. Response is not
coming, Does it not work on Emulators?
