### ISSUE TITLE
Issue implementing SDK 1.7

### ISSUE THREAD

**Issue by lovish888** [MSG91/sendotp-android#52]
I am getting the following error while implementing version 1.7 of the SDK:

Could not GET 'https://dl.bintray.com/walkover/Android-Libs/com/msg91/sendotpandroid/library/library/1.7/library-1.7.pom'. Received status code 403 from server: Forbidden

When I use version 1.3.8, it works fine.

**Comment by devnilspatel** [comment]
@lovish888  I am getting same error, have you fixed it ?

**Comment by lovish888** [comment]
Nope. Waiting for the response from Msg91 team.

**Comment by abhijeetvijai** [comment]
This library is now outdated. Use this https://github.com/walkovermsg91/sendotp-android
