### ISSUE TITLE
Onverified not getting called for mobile with Android OS Version 8.1.0

### ISSUE THREAD

**Issue by bhavifm** [MSG91/sendotp-android#6]
I have given below  permission in manifest.xml and before sending message i wil check below permission.

   " uses-permission android:name="android.permission.RECEIVE_SMS"  "
  " uses-permission android:name="android.permission.READ_SMS"  "

Here problem is after giving permission also auto verify not happening because _OnVerified_ callback not triggering in code.

   @Override
    public void onVerified(String var1) { 
}

I checked in marshamallow and noughat also its working perfect but problem is with Android OS Version 8.1.0

Please help.

**Comment by IrshadAndroid** [comment]
Hi, Thank-you for report us. This issue is resolved you can use the latest version .
